name: 🐛 Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please fill out the form below.

  - type: input
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the problem.
      placeholder: Describe the issue clearly
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How do we reproduce the bug?
      placeholder: Step-by-step instructions
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: Environment info
      description: OS, browser, Node version, etc.
      placeholder: e.g., MacOS 14.5, Node 18
    validations:
      required: false
