name: 💡 Feature Request
description: Suggest an idea or improvement
title: "[Feature]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your idea! Please fill out this form to help us understand it.

  - type: input
    id: feature-title
    attributes:
      label: Feature summary
      description: What's the feature or enhancement you're suggesting?
      placeholder: Short, clear title
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What problem would this feature solve?
      placeholder: Describe the user problem or pain point
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Suggested solution
      description: If you have an idea of how it could work, share it here
      placeholder: Optional — mockups, examples, or behavior
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you tried other workarounds or tools?
      placeholder: Optional
    validations:
      required: false
