name: Feature Request
about: Suggest an idea or enhancement for FixIt
labels: enhancement
assignees: ''Is your feature request related to a problem?Please describe what problem you're trying to solve.
Describe the solution you'd likeA clear and concise description of what you want to happen.
Describe alternatives you've consideredAny alternative solutions or features you’ve thought about.
Additional contextAdd any other context or screenshots that might help explain your feature idea.