name: Pull Request Handler

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write

jobs:
  pull-requests:
    uses: coedevtech/.github/.github/workflows/pull-requests.yml@main
