name: Release Fixit

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Clear vendor and regenerate lock file
        run: |
          rm -rf vendor
          composer update --no-interaction --prefer-dist --no-progress --optimize-autoloader

      - name: Run tests
        run: ./vendor/bin/pest

      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        with:
          release-type: php
          token: ${{ secrets.RELEASE_TOKEN }}
